# Generated by Django 4.1 on 2022-09-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_likepost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likepost",
            old_name="post_is",
            new_name="post_id",
        ),
    ]
